# **Chapter 02. 파이썬을 활용한 데이터 전처리**
> 파이썬을 활용한 데이터 전처리를 위해 Numpy, Pandas의 전반적인 내용을 살펴볼 것이다.

---
**< 목차 >**
> 2-0. 라이브러리(Libarary)란?<br>
2-1. Numpy 란?<br>
2-2. 배열(array) 슬라이싱과 정렬<br>
2-3. 행렬(martix) 연산과 성능

## 2-0. 라이브러리(Library)란?
> - 라이브러리는 쉽게 말하면 미리 만들어진 함수와 메소드로 이루어진 모듈들의 집합이다.<br>
- 자주 사용하는 기능들은 코드를 직접 작성할 필요 없이 만들어진 라이브러리를 불러와서 사용하면 편리하게 프로그래밍을 할 수 있다.
- Colab은 자주 사용되는 여러 라이브러리들이 미리 설치되어 있다.

> 라이브러리는 `import`를 통해서 불러올 수 있다.

In [ ]:
import numpy

> 필요하다면 `as`를 통해서 명령어를 원하는 문자로 단축해서 쓸 수 있도록 지정할 수도 있다.

In [2]:
import numpy as np

> 만일 설치되어 있지 않은 라이브러리를 import하는 경우는 에러가 발생한다.
- 이 경우는 `!pip install (라이브러리)` 명령어를 통해 colab에 라이브러리를 설치 후 사용하자.

In [ ]:
# 설치하지 않은 경우 에러가 발생한다.
import selenium

ModuleNotFoundError: ignored

In [ ]:
!pip install selenium

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 981 kB 28.4 MB/s 
     |████████████████████████████████| 139 kB 41.0 MB/s 
     |████████████████████████████████| 358 kB 50.7 MB/s 
     |████████████████████████████████| 55 kB 4.0 MB/s 
     |████████████████████████████████| 4.1 MB 50.2 MB/s 
     |████████████████████████████████| 58 kB 6.3 MB/s 
  Attempting uninstall: urllib3
    Found existing installation: urllib3 1.24.3
    Uninstalling urllib3-1.24.3:
      Successfully uninstalled urllib3-1.24.3
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
requests 2.23.0 requires urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1, but you have urllib3 1.26.11 which is incompatible.


In [ ]:
import selenium
# 에러가 발생하지 않는다.

> 불러온 라이브러리는 해당 라이브러리의 문법에 맞춰 사용하도록 하자.

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## 2-1. Numpy 란?
> - ***Numerical Python***의 줄임말로, 파이썬을 사용한 산술 계산에 가장 중요한 패키지 중 하나이다.
- 핵심 기능 중 하나인 N차원 배열의 `ndarray`를 통해 대규모 데이터 집합을 다루는데 매우 유용하다.
    - **ndarray**는 같은 종류의 데이터를 담을 수 있는 포괄적인 다차원 배열을 의미한다.
- 데이터 분석에서 대부분 **Pandas**와 함께 사용한다.
- 보통 numpy를 import할 때 편의상 `np`로 사용하는 경우가 많다.

In [ ]:
import numpy as np

> numpy는 배열의 축(axis)의 수에 따라 차원이 달라진다.
- axis는 0부터 순차적으로 1차원, 2차원, 3차원...을 뜻한다.
    - `axis=2` : 3차원
- `np.shape()` 함수를 사용하면 해당 데이터 속 각 차원의 크기를 알려준다.

In [ ]:
# 1차원 데이터
array1 = np.array([1,2,3])
np.shape(array1)

# (3,)는 '1차원에 3개의 값이 있다'는 의미이다.

(3,)

In [ ]:
# 2차원 데이터
array2 = np.array([[1,2,3],
                   [4,5,6]])
np.shape(array2)

# (2,3)은 '1차원(axis0, 행)에 2개의 값, 2차원(axis1, 열)에 3개의 값이 있다'는 의미이다.

(2, 3)

In [ ]:
# 3차원 데이터
array3 = np.array([[[1,2,3],
                    [4,5,6]],
                   [[7,8,9],
                    [10,11,12]]])
np.shape(array3)

# (2,2,3)은 '1차원(axis=0)에 2개의값, 2차원(axis=1)에 3개의 값, 3차원(axis=2)에 2개의 값이 있다'는 의미이다.

(2, 2, 3)

## 2-2. 배열(array) 슬라이싱과 정렬

### **배열(array) 생성하기**
> 1. `array 함수` 사용
2. numpy의 자체의 배열 생성 함수 사용

array 함수 사용하기

> array 함수를 이용하여 리스트, 튜플 혹은 다른 순차형 데이터를 ndarray 배열로 변환할 수 있다.

In [ ]:
data = [1,2,3,4,5,6,7]

In [ ]:
np.array(data)

array([1, 2, 3, 4, 5, 6, 7])

> 같은 길이를 가진 리스트를 내포한 데이터는 다차원 배열로 변환된다.

In [ ]:
data = [[1,2,3],[4,5,6]]

In [ ]:
np.array(data)

array([['1', '2', '3'],
       ['4', '5', '6']], dtype='<U1')

> 같은 형식의 데이터를 가지는 array 특성상 데이터의 자료형을 알아서 추측하여 설정해주지만,<br>
`dtype` 옵션을 통해 데이터의 자료형을 지정해줄 수도 있다.

In [ ]:
data = [[1,2,3],[4,5,6]]
np.array(data)

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.array(data, dtype='float')

array([[1., 2., 3.],
       [4., 5., 6.]])

In [ ]:
np.array(data, dtype='str')
# 이때 dtype으로 나오는 '<U1'은 '유니코드 문자열'이라는 의미이다.

array([['1', '2', '3'],
       ['4', '5', '6']], dtype='<U1')

numpy의 자체의 배열 생성 함수 사용

> `np.zeros()` : 주어진 dtype에 맞는 배열을 생성하고, 값을 0으로 채운다.

In [ ]:
# 0으로 이루어진 (3,3)의 배열 생성
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

> `np.ones()` : 주어진 dtype에 맞는 배열을 생성하고, 값을 1로 채운다.

In [ ]:
# 1로 이루어진 (3,4) 배열 생성
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

> `np.full()` : 주어진 dtype의 배열을 생성하고, 값을 주어진 값으로 채운다.

In [ ]:
# 10으로 이루어진 (2,3) 배열 생성
np.full((2,3), 10)

array([[10, 10, 10],
       [10, 10, 10]])

> `np.eye()` : 주어진 배열에 맞는 단위행렬을 생성한다.
- 좌상단에서 우하단까지의 값을 1로 채우고, 나머지를 0으로 채운 행렬 단위행렬이라고 한다.

In [ ]:
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

> `np.arange()` : 파이썬의 내장 함수 range와 유사하지만 array 배열을 반환해준다.

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(4,12,2)

array([ 4,  6,  8, 10])

> `np.linspace()` : 원하는 구간의 등간격인 값을 구해준다.
- 그래프를 그릴 때 유용하게 사용한다.
- 'np.linspace(시작값, 끝값, 간격개수)'의 형식이다.

In [ ]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
np.linspace(0,15,4)

array([ 0.,  5., 10., 15.])

### **슬라이싱 (Slicing)**
> - **데이터의 슬라이싱**은 데이터의 부분집합이나 개별 요소를 선택하여 추출하는 것이다.

1차원 데이터 슬라이싱
> - 1차원 데이터는 기본적인 파이썬 슬라이싱과 유사하게 동작한다.
- 파이썬은 **제로인덱스**를 사용한다는 것을 다시 한 번 상기하자.

In [11]:
arr = np.array([1,2,3,4,5])

In [7]:
# index가 0인 데이터 슬라이싱
arr[0]

1

In [9]:
# index가 3인 데이터 슬라이싱
arr[3]

4

다차원 데이터 슬라이싱
> - 다차원 데이터의 슬라이싱은 첫 번쨰 대괄호[ ]부터 하나씩 큰 차원의 index를 의미한다.
    - 1차원: arr[행index], 2차원: arr[행index][열index], ...
- 쉼표를 기준으로 슬라이싱 할 수도 있다.
    - arr[행index, 열index, ...]
    - 차원이 커질수록 콤마(,)를 기준으로 기준값이 하나씩 더 늘어난다.

In [12]:
arr2D = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]])

In [16]:
# 1차원의 3번째 데이터 슬라이싱(1행,3열)
arr2D[0][2]

3

In [17]:
# 2차원의 4번째 데이터 슬라이싱(2행,4열)
arr2D[1][3]

8

> 슬라이싱에서 [ : ] 로 슬라이싱 하면 해당 차원의 모든 데이터를 선택한다.

In [18]:
# 4열의 데이터 모두 선택
arr2D[:, 3]

array([ 4,  8, 12])

In [20]:
# 2행의 데이터 모두 선택
arr2D[1, :]

array([5, 6, 7, 8])

구간 슬라이싱
> 파이썬의 슬라이싱과 유사한 형식으로 구간 슬라이싱을 할 수도 있다.

In [27]:
arr = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12],
                [13,14,15,16]])

In [30]:
# 3행부터 슬라이싱
arr[2:]

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [33]:
# 3행까지 슬라이싱
arr[:3]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [34]:
# 2,3 열 슬라이싱
arr[:, 1:3]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

> 구간 슬라이싱을 활용하여 데이터의 중간에 원하는 부분만 슬라이싱 할 수도 있다.

In [42]:
# 2,3행의 1,2열 슬라이싱
arr[1:3, 0:2]

array([[ 5,  6],
       [ 9, 10]])

> [ :: ] 을 사용하여 특정 간격을 기준으로 슬라이싱 할수도 있다.

In [36]:
# 2칸 간격으로 행을 추출 (1,3행)
arr[::2]

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [37]:
# 2칸 간격으로 열을 추출 (1,3열)
arr[:, ::2]

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [13, 15]])

> [ -1 ]을 입력하면 마지막 차원의 데이터를 슬라이싱한다.

In [38]:
# 마지막 행 슬라이싱 (4행)
arr[-1]

array([13, 14, 15, 16])

In [ ]:
# 마지막 열 슬라이싱 (4열)
arr[:, -1]

### Fancy 인덱싱
> Fancy indexing은 특정 index에 해당하는 위치의 데이터만 뽑고 싶을 때 사용

In [45]:
arr = np.arange(16).reshape(4,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [47]:
# 3열 4행의 값 추출
arr[2,3]

11

In [48]:
# 1,3행 추출
arr[[0,2], :]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [49]:
# 1,4열 추출
arr[:, [0,3]]

array([[ 0,  3],
       [ 4,  7],
       [ 8, 11],
       [12, 15]])

> Fancy indexing에서 다차원 indexing은 조금 다르게 동작한다.
- 아래 예시의 arr[[0,2], [1,3]]은 해당 행과 열 데이터의 겹치는 부분인 [1,3]와 [9,11]이 슬라이싱 되는 것이 아닌 [1,11]이 슬라이싱 된다.
- Fancy indexing에서 해당 코드는 [0,1]의 위치값 [1]과, [2,3]의 위치값[11]을 슬라이싱한다.

In [51]:
# index[0,1]의 값과 index[2,3]의 값 추출
arr[[0,2], [1,3]]

array([ 1, 11])

In [56]:
# 1,3행의 2,4열을 전부 구하고 싶은 경우
arr[[0,2]][:,[1,3]]

array([[ 1,  3],
       [ 9, 11]])

### Boolean 인덱싱
> - Boolean 값인 True와 False를 이용하여 특정 조건을 만족하는 True 값만 슬라이싱
> - indexing 하고자 하는 데이터와 불리언 배열의 크기가 같아야만 indexing이 가능하다.

In [64]:
arr = np.arange(16).reshape((4,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [74]:
boolean = np.array([[True, True, False, False],
                    [False, False, True, True],
                    [True, False, True, False],
                    [False, True, False, True]])
boolean

array([[ True,  True, False, False],
       [False, False,  True,  True],
       [ True, False,  True, False],
       [False,  True, False,  True]])

In [76]:
arr[boolean]

array([ 0,  1,  6,  7,  8, 10, 13, 15])

> 조건을 통해 Boolean 배열을 만들어서 대입할수도 있다.

In [77]:
arr > 8

array([[False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [79]:
# [arr>8]의 값이 boolean 배열이기 때문에 조건만 대입하면 바로 슬라이싱 가능
arr[arr>8]

array([ 9, 10, 11, 12, 13, 14, 15])

### 배열 차원 변환
> - `np.reshape()`를 활용하면 원하는 차원으로 데이터를 변환 가능하다.
    - 'arr.reshape(행, 열)' 의 형식
- 단, 변환하려는 차원과 데이터의 크기가 맞지 않으면 변환되지 않는다.

In [84]:
arr1 = np.arange(12)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [85]:
# 3행 4열의 2차원 데이터로 변환
arr2 = arr1.reshape(3,4)
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

> 데이터의 크기를 모를 경우 `np.shape()`를 이용하면 알 수 있다.

In [87]:
np.shape(arr2)

(3, 4)

> 차원을 입력할 때 '-1'을 입력하면 자동으로 차원을 계산하여 넣어준다.

In [86]:
arr3 = arr1.reshape(2,-1)
arr3

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

### 정렬(sort)
> - `np.sort()`를 활용하여 데이터를 정렬할 수 있다.
- 기본 디폴트 설정은 오름차순이다.
    - 정렬 옵션으로 [::-1]을 추가하면 내림차순으로 바꿀 수 있다.

1차원 정렬

In [98]:
arr = np.array([10,5,3,8,6,2,9,1,4,7])

In [99]:
np.sort(arr)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [103]:
np.sort(arr)[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

N차원 정렬

In [104]:
arr = np.array([[2, 11, 6, 9],
                [1, 10, 16, 5],
                [8, 15, 14, 3],
                [12, 7, 13, 4]])
arr

array([[ 2, 11,  6,  9],
       [ 1, 10, 16,  5],
       [ 8, 15, 14,  3],
       [12,  7, 13,  4]])

> 다차원의 정렬은 축(axis)을 설정하여 정렬 방향을 선택할 수 있다.

In [106]:
# 행 방향 정렬 (위에서 아래 방향으로 정렬)
np.sort(arr, axis=0)

array([[ 1,  7,  6,  3],
       [ 2, 10, 13,  4],
       [ 8, 11, 14,  5],
       [12, 15, 16,  9]])

In [107]:
# 열 방향 정렬 (왼쪽에서 오른쪽으로 정렬)
np.sort(arr, axis=1)

array([[ 2,  6,  9, 11],
       [ 1,  5, 10, 16],
       [ 3,  8, 14, 15],
       [ 4,  7, 12, 13]])

### 유용한 Numpy 함수

> - `np.sum()` : 배열 전체 혹은 특정 축에 대한 모든 원소 합 계산

In [110]:
arr = np.arange(16).reshape(4,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [114]:
# 전체합
np.sum(arr)

120

In [115]:
# 특정 축의 합 (열방향)
np.sum(arr, axis=1)

array([ 6, 22, 38, 54])

> - `np.mean()` : 배열 전체 혹은 특정 축에 대한 산술평균을 계산

In [118]:
# 전체 평균
np.mean(arr)

7.5

In [119]:
# 특정 축의 평균 (행방향)
np.mean(arr, axis=0)

array([6., 7., 8., 9.])

> - `np.min()` : 최소값
- `np.max()` : 최대값

In [121]:
np.min(arr), np.max(arr)

(0, 15)

> - `np.argmin()` : 최소값의 index 반환
- `np.argmax()` : 최대값의 index 반환

In [126]:
np.argmin(arr), np.argmax(arr)

(0, 15)

> - `np.where()` : 특정 값의 index를 반환

In [132]:
np.where(arr==6)
# 행 기준으로 index 1, 열 기준으로 index 2에 있다는 의미이다.

(array([1]), array([2]))

## 2-3. 행렬(matrix) 연산과 성능